### ISSUE TITLE
Colorblind support

### ISSUE THREAD

**Issue by TiloBuechsenschuss** [shemetz/pf2e-see-simple-scale-statistics#2]
The idea of this module is great, being able to quickly see what a creature is good at would be very useful. However, I'm pretty colorblind and can't easily see the differences at a glance.
Is there any chance you could add colorblind support? Absolutely gated behind a module setting, so it doesn't mess with the sheet if you don't want it.
Maybe add a tooltip by hovering when the display is on. Or maybe also add a small icon before or after colored displays (maybe numbers? 1 would be extreme, 5 would be terrible?).
I understand if that can't be easily done, just disregard this then.

**Comment by shemetz** [comment]
Option 1 - Are there colors you discern more easily?  it can be pretty simple for me to just change the 5 colors on the scale to a different gradient that can be easier for you specifically.

Option 2 - I can try to assign different styles rather than different colors.  E.g. different degrees of bold, italics, underline, etc.  Possibly different fonts.

Option 3 would be adding little icons or digits, I can try but I expect it to look bad because there isn't much more horizontal space on the sheet.

Option 4 - tooltips on hover, like you said.  This might be simple, not sure, but the big issue there is that you can't tell at a glance what is strong and what is weak (and so the experience is worse).

Do you have preferences or suggestions regarding these, especially 1 and 2?

**Comment by TiloBuechsenschuss** [comment]
I've got red–green color blindness, but especiall color gradients are kinda iffy for me. So some harsh differences are much better than a gradient for me. So extreme vs high work great as is, but low & terrible are kinda same-ish to me. 
But I think there are four or five different color blindnesses, so you'll either have to accomodate a bunch of options or go with something different than colors. That's why I suggested icons. 
Styles would work well, I think. Bolder for higher, italic for lower could be an idea. Different fonts are also a good idea. As different as possible, I think, so you can easily tell at a glance.

**Comment by shemetz** [comment]
How about this?  

Using borders:  Inset, Groove, Dotted, Dashed, Solid - to match Terrible, Low, Moderate, High, Extreme.

![image](https://user-images.githubusercontent.com/6516621/197360163-ad2ffaaf-e934-4ec4-bda6-0da4255b3a70.png)


Can also be bottom-border only:

![image](https://user-images.githubusercontent.com/6516621/197360326-2503350c-ed8f-4c76-b162-80b1253283d9.png)

**Comment by TiloBuechsenschuss** [comment]
That's pretty great! Makes a quick comparison very easy. ^-^ Thanks a bunch for the effort! :-)
I'd recommend adding it to the button as a legend, though.

**Comment by shemetz** [comment]
@TiloBuechsenschuss which do you prefer?  Full border or top border?

**Comment by TiloBuechsenschuss** [comment]
Full border's easier to quickly make out at a glance, so that one.

**Comment by shemetz** [comment]
Added in v1.2.0 :]

**Comment by TiloBuechsenschuss** [comment]
> Added in v1.2.0 :]

Thanks a bunch! ^-^
